
DROP SCHEMA FINANCE CASCADE;

CREATE SCHEMA FINANCE

DROP TABLE IF EXISTS FINANCE."MANUAL_JOURNAL_ENTRY_TRANSACTION";

CREATE TABLE FINANCE."MANUAL_JOURNAL_ENTRY_TRANSACTION" (
    "ID" SERIAL NOT NULL,
    PRIMARY KEY ("ID"),
    --TRANSACTION
    "COMPANY_ID" TEXT,
    "ENTRY_ID" TEXT,
    "BUSINESS_UNIT_ID" TEXT,
    "ACCOUNT_NO" TEXT,
    "AMOUNT" NUMERIC(20, 2),
    "ACCOUNTING_DATE" DATE,
    "DATA_TYPE" TEXT,
    --COMMENTS
    "REMARKS" TEXT,
    "COMMENTS" TEXT,
    "FOLLOW_UP_STATUS" TEXT,
    --TYPE
    "ENTRY_TYPE" TEXT,
    "SOURCE_SYSTEM" TEXT,
    "REVERSED" TEXT,
    "APPROVAL" TEXT,
    "REVERSING_DATE" DATE,
    --AUDIT
    "DATE_CREATED" DATE,
    "USER_CREATED" TEXT,
    "DATE_CLOSED" DATE,
    "USER_CLOSED" TEXT,
    "DATE_POSTED" DATE,
    "USER_POSTED" TEXT,
    --TRANSACTION
    "COMPANY" TEXT,
    "BUSINESS_UNIT" TEXT,
    "ACCOUNT" TEXT,
    "ACCOUNT_TYPE" TEXT,
    "RAD_DATA" JSONB,
    "PERIOD_ID" TEXT,
    --COMPUTED
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "FISCAL_YEAR" INTEGER GENERATED ALWAYS AS (
        CASE
            WHEN EXTRACT(MONTH FROM "ACCOUNTING_DATE") >= 10 THEN EXTRACT(YEAR FROM "ACCOUNTING_DATE") + 1
            ELSE EXTRACT(YEAR FROM "ACCOUNTING_DATE")
        END
    ) STORED
);

DROP TABLE IF EXISTS FINANCE."MANUAL_BUDGET";

CREATE TABLE FINANCE."MANUAL_BUDGET" (
    "ID" SERIAL NOT NULL,
    PRIMARY KEY ("ID"),
    --TRANSACTION
    "COMPANY_ID" TEXT,
    "BUDGET_ID" TEXT,
    "BUSINESS_UNIT_ID" TEXT,
    "ACCOUNT_NO" TEXT,
    "RAD_DATA" JSONB,
    "AMOUNT" NUMERIC(20, 2),
    "ACCOUNTING_DATE" DATE,
    "DATA_TYPE" TEXT,
    --COMPUTED
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "FISCAL_YEAR" INTEGER GENERATED ALWAYS AS (
        CASE
            WHEN EXTRACT(MONTH FROM "ACCOUNTING_DATE") >= 10 THEN EXTRACT(YEAR FROM "ACCOUNTING_DATE") + 1
            ELSE EXTRACT(YEAR FROM "ACCOUNTING_DATE")
        END
    ) STORED
);
